#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.7.0
// Descriptor size: 24 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 1 |
// +----------+-------+-------------------+
static const u8 PROGMEM hidReportDescriptor[] = 
{
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x04,          // UsageId(Joystick[0x0004])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x05, 0x02,          //     UsagePage(Simulation Controls[0x0002])
    0x09, 0xC5,          //     UsageId(Brake[0x00C5])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
};